### ISSUE TITLE
Integrate EDD Software Licensing

### ISSUE THREAD

**Issue by brashrebel** [dragonslayerindustries/learndash-mailchimp#1]
For our plugins, we use the Software Licensing addon for Easy Digital Downloads to connect with our store, validate licenses and facilitate plugin updates.

**Comment by brashrebel** [comment]
Here's the class from EDD: https://github.com/easydigitaldownloads/EDD-License-handler

Here's a couple plugins using the EDD SL updater:
- https://github.com/easydigitaldownloads/edd-message
- https://github.com/realbigplugins/psp-edd

**Comment by objectsweb** [comment]
I have one question regarding this point, is the work flow will be as following: 
1. Student download go to download a file
2. display a subscribe button to subscribe after downloading 
3. New segments will be created called LD- Downloders for example that contain all users who did some downloads

**Comment by brashrebel** [comment]
@objectsweb ah, no. Sorry if I was unclear. I may have assumed that you were familiar with EDD's Software Licensing already. My apologies. Here's how it works:

We are going to sell this plugin on realbigplugins.com. We are using Easy Digital Downloads and the Easy Digital Downloads Software Licensing extension on realbigplugins.com to sell and license our plugins. Software Licensing makes it possible to allow customers to purchases licenses for software products and then activate those licenses within the product.

In order for Software Licensing to work, it needs to be active on the site which is selling the software and the license handler I mentioned above needs to be implemented in the codebase of the plugin which is being sold. It's fairly simple to implement and, when done, will make it so customers who purchase LearnDash MailChimp will get a field to activate their license key within the plugin's settings. If they have a valid license it will be successful, otherwise it will say the license is invalid.

See documentation for Software Licensing [here](http://docs.easydigitaldownloads.com/article/383-automatic-upgrades-for-wordpress-plugins).

I will share privately with you some more examples which you can copy from.

**Comment by objectsweb** [comment]
Software Licensing to LearnDash MailChimp plugin has been done. please provide the following data: 
1. Site URL or the store URL  (where we can publish our plugin into) 
2. Product name or item name  (The name of the product in that site)

**Comment by brashrebel** [comment]
Awesome!

*Store URL:* `https://realbigplugins.com`
*Product Name:* `LearnDash - MailChimp`
*Download ID:* `3157`

Please note: As you'll see [here](http://docs.easydigitaldownloads.com/article/383-automatic-upgrades-for-wordpress-plugins), item_id is preferred to item_name. The plugins I shared with you might use item name but it is now more appropriate and safer to use the item_id value instead.

**Comment by objectsweb** [comment]
@brashrebel Download ID is not needed by the EDD licensing. it just need product name and license key

**Comment by brashrebel** [comment]
@objectsweb actually the product name is only a fallback if item_id is not used. See this doc in step 3: http://docs.easydigitaldownloads.com/article/383-automatic-upgrades-for-wordpress-plugins

**Comment by objectsweb** [comment]
@brashrebel Product ID has been added to the plugin instead of product name please check.

**Comment by objectsweb** [comment]
Kindly inform me if we still have any clarifications according to this point to close it?

**Comment by brashrebel** [comment]
Just tested and this worked perfectly!! 🎉
