### ISSUE TITLE
Fail gracefully if LearnDash is not active

### ISSUE THREAD

**Issue by brashrebel** [dragonslayerindustries/learndash-mailchimp#13]
No fatal errors or anything. We should show a nice admin notice indicating that LearnDash is required and also showing our required version.

**Comment by objectsweb** [comment]
Where do you want to add this notice?

**Comment by brashrebel** [comment]
I just shared with you privately two other LearnDash extensions which you can model after. They both display an admin notice if they are activated and LearnDash is not or it is the wrong version of LearnDash.

**Comment by brashrebel** [comment]
@objectsweb typically this is determined by your code. If you require anything specific in LearnDash than you'll need to make sure we don't break in versions before your requirement existed. If you don't know which version you require than I'd be safe and go with something recent like 2.2 as long as you can test it on that version and it still works.

**Comment by objectsweb** [comment]
We have added 2.2 as a minimum version

**Comment by brashrebel** [comment]
This is close but not exact. Right now if LearnDash is not active, the plugin cannot be activated and throws a fatal error plus this message:

https://cloudup.com/ccUQanVPc1K

Additionally the text should read:

> LearnDash MailChimp requires LearnDash version 2.2 or greater.

**Comment by objectsweb** [comment]
This is close but not exact. Right now if LearnDash is not active, the plugin cannot be activated and throws a fatal error

**Objects comment: Fetal error is the default message that word-press generate if something required for installing some plugins**


LearnDash MailChimp requires LearnDash version 2.2 or greater.

**Objects comment: Message Changed, kindly check**

**Comment by brashrebel** [comment]
Great! Though, typically how we handle those kinds of things in plugins is by checking for a dependency's existence first. `if ( ! class_exists( 'LearnDash' ) ) : return;` or something more sophisticated than that. That's what we call failing gracefully. We check for the dependency and then if it is not there, stop any functionality and display a helpful message to the user.

Is it possible to make sure that users who do not have LearnDash active get only the helpful message and no PHP errors?

**Comment by objectsweb** [comment]
OK! we are double checking this point as well and I'll inform you once we have done.

Thanks.

**Comment by objectsweb** [comment]
- Done, please check.

Now user who don't have LearnDash active will see our helpful message only,

Thanks.
