### ISSUE TITLE
Course options need more explanation

### ISSUE THREAD

**Issue by brashrebel** [dragonslayerindustries/learndash-mailchimp#19]
It is not totally clear what happens when checking these boxes, in particular the first three:

https://cloudup.com/c8rFy9qVO3B

Does this make a subscribe checkbox appear? If so, can we add a heading above these three or just add to each label the text "Show a checkbox for subscribing..." and then separate the last option because it is different.

**Comment by objectsweb** [comment]
These check-boxes just act as an admin controller by giving the admin the ability to control subscription button displaying, please check the following description: 
1. Before signing up for a course means --> Subscription form will appear if student didn't register to the course **[if not checked subscription form wont appear]**
2. During the course means --> Subscription form will appear while student still doing the course **[if not checked subscription form wont appear ]**
3. After completing the course means --> Subscription form will appear when student has finished the course **[if not checked subscription form wont appear]**
4. Auto subscribe means --> by checking this one, admin force student  to subscribe the course if he/ she register into it **[This feature useful if admin has a certain peace of info need to be delivered (announced) to all students in a specific course]**

Kindly check the above comments and if you still have some clarifications don't hesitate to contact us.

**Comment by objectsweb** [comment]
@brashrebel We added more descriptive texting for this point, please check.
