### ISSUE TITLE
Some typos in the code

### ISSUE THREAD

**Issue by brashrebel** [dragonslayerindustries/learndash-mailchimp#23]
- [x] [checbox](https://github.com/dragonslayerindustries/learndash-mailchimp/blob/master/includes/classes/front/Ld_MailChimp_Add_Course.php#L22) - > checkbox
- [x] [befor](https://github.com/dragonslayerindustries/learndash-mailchimp/blob/master/includes/classes/front/Ld_MailChimp_Add_Course.php#L30) - > before (occurs twice on this line)
- [x] [before](https://github.com/dragonslayerindustries/learndash-mailchimp/blob/master/includes/classes/front/Ld_MailChimp_Add_Course.php#L37) - > before
- [x] [checbox](https://github.com/dragonslayerindustries/learndash-mailchimp/blob/master/includes/classes/front/Ld_MailChimp_Add_Course.php#L60) - > checkbox
- [x] [befor](https://github.com/dragonslayerindustries/learndash-mailchimp/blob/master/includes/classes/front/Ld_MailChimp_Add_Course.php#L68) - > before
- [x] [befor](https://github.com/dragonslayerindustries/learndash-mailchimp/blob/master/includes/classes/front/Ld_MailChimp_Add_Course.php#L72) - > before
- [x] [acess](https://github.com/dragonslayerindustries/learndash-mailchimp/blob/master/includes/classes/front/Ld_MailChimp_Add_Course.php#L83) - > access
- [x] [confilect](https://github.com/dragonslayerindustries/learndash-mailchimp/blob/master/learndash-mailchimp.php#L40) - > conflict
- [x] [comment](https://github.com/dragonslayerindustries/learndash-mailchimp/blob/master/learndash-mailchimp.php#L96) - > not a typo, just doesn't apply to this codebase
- [x] [segement](https://github.com/dragonslayerindustries/learndash-mailchimp/blob/master/includes/classes/shortcodes/Ld_MailChimp_Shortcodes_Course.php#L21) - > segment
- [x] [subscriped](https://github.com/dragonslayerindustries/learndash-mailchimp/blob/master/includes/classes/shortcodes/Ld_MailChimp_Shortcodes_Course.php#L30) - > subscribed
- [x] [befor](https://github.com/dragonslayerindustries/learndash-mailchimp/blob/master/includes/classes/shortcodes/Ld_MailChimp_Shortcodes_Course.php#L77) - > before
- [x] [befor](https://github.com/dragonslayerindustries/learndash-mailchimp/blob/master/includes/classes/shortcodes/Ld_MailChimp_Shortcodes_Course.php#L91) - > before

**Comment by objectsweb** [comment]
OK! Clear.

**Comment by objectsweb** [comment]
@brashrebel Done, please check

**Comment by brashrebel** [comment]
Great! I did just find:

- [ ] [messsage](https://github.com/dragonslayerindustries/learndash-mailchimp/blob/master/includes/classes/front/Ld_MailChimp_Add_Course.php#L36) - > message (twice)
- [ ] [messsage](https://github.com/dragonslayerindustries/learndash-mailchimp/blob/master/includes/classes/front/Ld_MailChimp_Add_Course.php#L74) - > message (twice)
- [ ] [messsage](https://github.com/dragonslayerindustries/learndash-mailchimp/blob/master/includes/classes/front/Ld_MailChimp_Add_Course.php#L77) - > message
- [ ] [messsage](https://github.com/dragonslayerindustries/learndash-mailchimp/blob/master/includes/classes/front/Ld_MailChimp_Add_Course.php#L78) - > message

And noted that the "comment" one from above is about WooCommerce and Cubepoints but it should state LearnDash.

**Comment by objectsweb** [comment]
@brashrebel Done, please check.
