### ISSUE TITLE
Don't require shortcode for subscription form in courses

### ISSUE THREAD

**Issue by brashrebel** [dragonslayerindustries/learndash-mailchimp#27]
After testing and thinking a little bit, I think that we should separate the subscription form functionality a little more. I think we should make the shortcode always output the subscription form, no matter what. It can be used primarily outside of the course pages for people who want to put it in their blog posts or marketing pages. But _within_ courses we shouldn't require the shortcode. We should just rely on the checkbox settings for the course. If the box is checked, the "Subscribe to our newsletter" feature will appear before the course content. No shortcode needed.

This is actually the behavior I expected when testing and was surprised to find out that the shortcode was required. I think it would be a much better experience for users to have to only check the box and just have the shortcode available when they want the form somewhere _else_.

**Comment by objectsweb** [comment]
In progress....

**Comment by objectsweb** [comment]
- Shortcode now always output the subscription form no matter the course status (before, after, and during)
- Shortcode can be used at any page and doesn't required in the courses pages
- Within courses pages, we have a check box if checked, then the subscription behavior will appear: 
> In case of Free type course --> check box from back-end fire another check box in the front-end 
> In case of Open/ But now/ Recurring type  course --> check box fire the subscription button

**Comment by brashrebel** [comment]
Just tested and this seems to be correct. Great work!
