### ISSUE TITLE
Run licensing on hook

### ISSUE THREAD

**Issue by brashrebel** [dragonslayerindustries/learndash-mailchimp#28]
Right now, all the code after [this line](https://github.com/dragonslayerindustries/learndash-mailchimp/blob/master/learndash-mailchimp.php#L115) exists in the global scope and is not fired at a specific instance. It is highly advisable to place this code inside a function or class method which gets run on a hook. `admin_init` is a good choice and one which our other LearnDash addons are using for the licensing code.

Also, this code being in the global scope means it always fires frontend or backend which isn't very efficient. Also, it results in an error message upon activation that:

> The plugin generated 2673 characters of unexpected output during activation. If you notice “headers already sent” messages, problems with syndication feeds or other issues, try deactivating or removing this plugin.

I believe putting this code inside a function and adding it on the `admin_init` hook will fix the problem.

**Comment by objectsweb** [comment]
This one has finished and code updated, kindly check.

**Comment by objectsweb** [comment]
- This one didn't happened here with me, could you please send a small video with it.

**Comment by brashrebel** [comment]
Here is a video of me installing and activating the .zip from here on a new dev site: https://www.dropbox.com/s/waow0e8grkrnlwl/ldmc-activation-bug.mov?dl=0

**Comment by objectsweb** [comment]
- Plugin updated but this issue still didn't appear here so it may be something related to your WordPress, please check if it still happened please provide the access data (link, username, and password) for the your Wordpress admin in order to check the issue here.

Thanks.

**Comment by brashrebel** [comment]
This is done and the issue was related to #32 which is closed so we're all set here.
