### ISSUE TITLE
Settings page

### ISSUE THREAD

**Issue by brashrebel** [dragonslayerindustries/learndash-mailchimp#3]
We need a settings page accessible from the LearnDash settings screen. Probably something like this with a new MailChimp tab in the upper right:
<img width="972" alt="screen shot 2017-07-01 at 7 23 31 am" src="https://user-images.githubusercontent.com/4993131/27761646-5180e046-5e2e-11e7-8d54-d7dc0a8dac98.png">

**Comment by objectsweb** [comment]
Done

**Comment by brashrebel** [comment]
Can we just call the tab "MailChimp" instead of "LD MailChimp Settings"?

Also, can we move the licensing for this integration to the LMS License tab instead of its own page?

**Comment by objectsweb** [comment]
Can we just call the tab "MailChimp" instead of "LD MailChimp Settings"?
**Done! please check** 


Also, can we move the licensing for this integration to the LMS License tab instead of its own page?
 
**Sometimes it causes some errors while mixing licenses in the same page, but we are double checking it**

**Comment by brashrebel** [comment]
Great! I believe I shared with you (possibly in Codeable) the LD Gradebook and the LD Slack integrations. You can use those as examples because they both implemented the licensing that way as I recall.

**Comment by objectsweb** [comment]
OK! we are double check it and I'll inform you once we have done.

Thanks.

**Comment by objectsweb** [comment]
Now LD-mailchimp license added to LMS license tab, Please check. 

Thanks.

**Comment by brashrebel** [comment]
Awesome!
