### ISSUE TITLE
Fatal error caused by requiring sfwd_lms

### ISSUE THREAD

**Issue by brashrebel** [dragonslayerindustries/learndash-mailchimp#32]
If LearnDash is installed in a directory not named `/sfwd_lms/` then the site crashes. We can never assume the name of another plugin's folder. Too dangerous. Fortunately, you can use `LEARNDASH_LMS_PLUGIN_DIR` instead because that should always be correct.

You'll only be able to replicate this if you change the name of the folder that LearnDash is in. In my setup, it is called `/learndash/` which will be rare but it will happen.

**Comment by objectsweb** [comment]
- Now it works whatever the learn-dash plugin name. please check and confirm.

Thanks

**Comment by brashrebel** [comment]
Looks great!
