### ISSUE TITLE
Font-size of Settings Saved Notice is inconsistent with the rest of WordPress

### ISSUE THREAD

**Issue by d4mation** [dragonslayerindustries/learndash-mailchimp#35]
The inline styling makes it far too large. Also, it may not need the `<strong>` tag around the entirety of the text.
![image](https://user-images.githubusercontent.com/7770631/29715242-7fec6d26-8974-11e7-9923-951ba259f208.png)

Here's one added by WordPress Core. Font-size defaults to `13px`
![image](https://user-images.githubusercontent.com/7770631/29715273-a251050c-8974-11e7-9093-9ba494426727.png)

**Comment by objectsweb** [comment]
- Font size has adjusted, please check.

**Comment by d4mation** [comment]
Fixed
