### ISSUE TITLE
Settings Page doesn't "match" the rest of LearnDash

### ISSUE THREAD

**Issue by d4mation** [dragonslayerindustries/learndash-mailchimp#36]
The Settings Page for this sticks out pretty terribly. It doesn't mesh with any of the other Settings Pages in LearnDash.

The LMS License tab has all its fields directly against the "background".
![image](https://user-images.githubusercontent.com/7770631/29715425-57a1281a-8975-11e7-809d-0d0a05be834c.png)

The General tab has all its field within one "group" with the save button on the right-hand side. Each other built-in Settings tab works this way:
![image](https://user-images.githubusercontent.com/7770631/29715572-e776c0bc-8975-11e7-8be0-2f8db61978f1.png)

LearnDash Slack (which I made) follows more of the standard WordPress Settings API pages (Like you'd see under Settings->General) and has Field Headings on the left and Fields on the right:
![image](https://user-images.githubusercontent.com/7770631/29715723-791e89be-8976-11e7-92bc-e13de29daeff.png)

However, LearnDash MailChimp seems to have a different "group" per setting. I think it would work better if it were more similar to one of the above examples.
![image](https://user-images.githubusercontent.com/7770631/29715789-c39d33fa-8976-11e7-9903-ca31188b02ea.png)

**Comment by objectsweb** [comment]
- Some enhancements done to the settings page and grouping has removed, please check.

**Comment by d4mation** [comment]
Overall looks much better. Additional comments are in #37 as that Issue had specific recommendations.
