### ISSUE TITLE
One global "Save Changes" button for the page rather than per "Group"

### ISSUE THREAD

**Issue by d4mation** [dragonslayerindustries/learndash-mailchimp#37]
This is somewhat related to both #36 and #34.

It seems that something like this would work better than the current solution which has a "Submit" button per "Group".

On initial load, only show the API Key field. There isn't much point in setting a "Subscribe message" if there isn't a valid API Key stored. As far as I can tell, there would be no reason in showing that message on the frontend to a user unless there is a valid API Key.

Once they've entered an API Key and hit a "Save Changes" button at the bottom of the page, the page refreshes as normal. Ideally, during this page refresh it should be checking the Validity of the API Key and setting your valid/invalid status in the Database as well.

If the API Key is valid, then show the remaining fields. The List and the Subscribe Message are just simple values stored in the database, so they should be able to get set normally when hitting "Save Changes" at the bottom of the screen.

The "Create Segments" button when there are missing Courses would need to stay as it is, since it processes some extra stuff on its end. However, maybe that should instead be placed within a Notice? It could be set to only show on this page if that's how it should be.

![image](https://user-images.githubusercontent.com/7770631/29716308-dd11ffb2-8978-11e7-9ad8-0a77efe8b1c1.png)

**Comment by objectsweb** [comment]
Some enhancements have done into to the settings pages following, please check: 

1. No grouping is found 
2. See Subscribe message only if the API key is valid 
3. Create Segments button now appear in the Notice messages

**Comment by d4mation** [comment]
Loaded the page and these notices appeared automatically. The "Create Segments" one should be showing, but not the one saying that they have been created successfully as I have taken no action.

Also, the create segments Notice needs some work. It should look more similar to my screenshot above so that it matches WordPress standards. I think you kept all the wrapping elements from the previous layout when you made it into a Notice.

![image](https://user-images.githubusercontent.com/7770631/29823453-ada67696-8c9c-11e7-9bd3-ec85f0ec12ad.png)

**Comment by d4mation** [comment]
Also, the "Save Changes" button is being clipped oddly. It has an unnecessary inline style applied to it that is causing this.

![image](https://user-images.githubusercontent.com/7770631/29823581-11f91f5e-8c9d-11e7-8246-a765de4af227.png)

**Comment by objectsweb** [comment]
- Done, check please.

**Comment by d4mation** [comment]
There is still a lot of strange spacing on the "Create Segments" notice. This is because you're including an entire `<table>` with inline styles in there. All that needs to be there is the `<form>`, the text itself and the submit button.

![image](https://user-images.githubusercontent.com/7770631/29969282-65681a6c-8eed-11e7-8e39-fc71ececdabd.png)

**Comment by d4mation** [comment]
Also, the "Create Segments" notice should probably be created using `error` instead of `updated` for consistency through WordPress. It is more of an Error Notice than a "You did something successfully" Notice.

**Comment by objectsweb** [comment]
There is still a lot of strange spacing on the "Create Segments" notice. This is because you're including an entire <table> with inline styles in there. All that needs to be there is the <form>, the text itself and the submit button.

> Table deleted, kindly check.

Also, the "Create Segments" notice should probably be created using error instead of updated for consistency through WordPress. It is more of an Error Notice than a "You did something successfully" Notice.

> we use error instead of updated class`, kindly check.

**Comment by brashrebel** [comment]
Looks good to me.

**Comment by d4mation** [comment]
Unnecessary tables in the "Create Segments" notice are still there.

![image](https://user-images.githubusercontent.com/7770631/30274679-783d486a-96cc-11e7-9ea5-78dc92e0e3e4.png)

**Comment by objectsweb** [comment]
ok this one is fixed as well @d4mation

**Comment by brashrebel** [comment]
Looks good to me.
