### ISSUE TITLE
Use a placeholder for the default "Subscribe Message" text rather than pre-filling it

### ISSUE THREAD

**Issue by d4mation** [dragonslayerindustries/learndash-mailchimp#38]
This field should use the `placeholder` attribute instead of setting the `value` to the default directly. If the user does not enter a value, it should stay blank instead of populating with the default.

When using `get_option()`, you can provide a default if no value exists.

So, in this case, you could use 

```
get_option( 'ld_subscribe_message', __( 'Subscribe to our newsletter', 'learndash-mailchimp' ) );
```
 in order to grab the default text if nothing is set by the user.

Also, in the code currently, the default text is not translatable. 

https://github.com/dragonslayerindustries/learndash-mailchimp/blob/bf1f3f31b1d93f1b62f317513f286ee8f0649799/includes/classes/admin/Ld_MailChimp_Setting.php#L196

**Comment by objectsweb** [comment]
Done, please check.

**Comment by d4mation** [comment]
Still some problems. Made a couple comments on the Commit.

**Comment by objectsweb** [comment]
- Done, Check please.

**Comment by d4mation** [comment]
Confirmed
