### ISSUE TITLE
Use WordPress' built-in Settings API instead of checking `$_POST` for the existence of values before rendering/saving

### ISSUE THREAD

**Issue by d4mation** [dragonslayerindustries/learndash-mailchimp#39]
This is what I'm talking about here. This should not be how this is done. 

https://github.com/dragonslayerindustries/learndash-mailchimp/blob/bf1f3f31b1d93f1b62f317513f286ee8f0649799/includes/classes/admin/Ld_MailChimp_Setting.php#L187-L218

WordPress has built in methods to handle this kind of thing and LearnDash has some built in methods for its fields. You can see them under `./includes/settings/settings-sections-fields/` in LearnDash. However, LearnDash's Fields Functions are admittedly limiting. When I made LearnDash Slack and when a coworker made LearnDash Gradebook, we determined rolling our own functions for the Fields were better.

For LearnDash Gradebook, you will want to look at `./admin/class-ld-gb-adminpage-settings.php` and `./admin/views/html-settings-general.php` to see them in action.

For LearnDash Slack, you will want to look at `./core/admin/class-learndash-slack-admin.php` specifically under the `admin_page()` and `register_options()` methods. Those methods are how the Settings Page gets automatically generated using WordPress' Settings API. The callback functions for each Field can be found at `./core/learndash-slack-settings-api.php`.

**Comment by d4mation** [comment]
Using LearnDash Slack as an example though, so I'm so closely utilizing the Settings API, may prove troublesome however due to the way LearnDash builds out its menus. It may be best to follow LearnDash Gradebook as an example so that you do not have use the crazy Filters I did in `./core/admin/settings-tab/class-learndash-slack-settings-tab.php` to make it work correctly.

**Comment by objectsweb** [comment]
Regarding this issue, we couldn't implement WordPress behavior because we have two separate actions that have to be done: 

1. Action1 --> API connection 
2. Action2 --> Listing and subscribe message 

- but WordPress behavior can be done if we only have one action to be done.

**Comment by d4mation** [comment]
If things are laid out similarly to what I laid out in #37, I don't think this will be an issue.

The API Connection would still need its own submit button (To save and test the validity of the API Key), but once a valid key is detected, the remaining fields could be shown. The remaining Fields (List Selection and Subscribe Message) should be able to be saved using one, global, Save Changes button.

In #37 I also laid out an alternative way to handle the segment creation button.

**Comment by objectsweb** [comment]
- #37 enhancements already done.
The API Connection would still need its own submit button (To save and test the validity of the API Key), but once a valid key is detected, the remaining fields could be shown.  **Done**

-  The remaining Fields (List Selection and Subscribe Message) should be able to be saved using one, global, Save Changes button. **Done**

- The new way of handling segment creation button **Done**

but this one can't be done here because as I told you above that we have two different actions that should done.

**Comment by d4mation** [comment]
Both of those actions can still be done though. I think you're misunderstanding me.

Those two actions will have to be done outside of the Settings API. That is a given.

However, you can still have the data for the Subscribe Message and the List Dropdown saved via the Settings API. Technically you could even save the API Key using the Settings API as well, but that may be overly complicated as you'd still need to properly check validity, so saving it at the same time as you do that may be easier.

**Comment by objectsweb** [comment]
- That means that the current behavior is accepted?

**Comment by d4mation** [comment]
No.

What you will need to do is make a callback function that runs `do_action( <some_parameter_provided_by_callback_function> )` and use that for all your special buttons/sub forms for those special use cases. By doing that, it will allow you to also use the Settings API for the other more simple forms like the List Dropdown and the Subscribe Message.

Here's how I did it in LearnDash Slack:

Hook Creation Callback Function
https://github.com/realbigplugins/learndash-slack/blob/master/core/learndash-slack-settings-api.php#L273-L295

Adding whatever HTML I want using that dynamically created Hook
https://github.com/realbigplugins/learndash-slack/blob/master/core/admin/class-learndash-slack-admin.php#L28-L29

**Comment by objectsweb** [comment]
Done, Check please.

**Comment by brashrebel** [comment]
@d4mation is there a chance you could do me a favor and check this issue please?

**Comment by d4mation** [comment]
All set.
