### ISSUE TITLE
Use add_settings_error() instead of manually building out Notices

### ISSUE THREAD

**Issue by d4mation** [dragonslayerindustries/learndash-mailchimp#40]
https://github.com/dragonslayerindustries/learndash-mailchimp/blob/bf1f3f31b1d93f1b62f317513f286ee8f0649799/includes/classes/admin/Ld_MailChimp_Setting.php#L193

The function `add_settings_error()` is a bit of a misnomer, because it can be used to show green "Updated/Success" messages as well.

https://codex.wordpress.org/Function_Reference/add_settings_error

This ties in with #39 as it is a part of the Settings API

**Comment by objectsweb** [comment]
Done, Please check.

**Comment by d4mation** [comment]
Confirmed
