### ISSUE TITLE
Use wp_nonce_field() instead of manually creating a nonce field

### ISSUE THREAD

**Issue by d4mation** [dragonslayerindustries/learndash-mailchimp#43]
https://codex.wordpress.org/Function_Reference/wp_nonce_field

https://github.com/dragonslayerindustries/learndash-mailchimp/blob/edbb429fe67ec83f358e5ba3a67d1811aff787a7/includes/classes/admin/Ld_MailChimp_Settings_Course.php#L43

**Comment by objectsweb** [comment]
Done, check please.

**Comment by d4mation** [comment]
Confirmed
