### ISSUE TITLE
Licensing implementation including LearnDash Core directly

### ISSUE THREAD

**Issue by d4mation** [dragonslayerindustries/learndash-mailchimp#44]
This is being done so that it can grab a prefix on a non-changing Hook Name. I'm using the same hook in LearnDash Slack but am statically defining it without problems.

https://github.com/dragonslayerindustries/learndash-mailchimp/blob/51f55ad724150cd0fa702aaa236bd6b8bb91e975/includes/classes/front/Ld_MailChimp_Licence_Page.php#L20-L29

LearnDash Slack using it without loading the main plugin file of LearnDash:
https://github.com/realbigplugins/learndash-slack/blob/9af179ee4605ea6775228060ecd7809301db1558/core/licensing/class-learndash-slack-licensing-field.php#L25-L26

**Comment by objectsweb** [comment]
- Provided Link is not accessible.  
https://github.com/realbigplugins/learndash-slack/blob/9af179ee4605ea6775228060ecd7809301db1558/core/licensing/class-learndash-slack-licensing-field.php#L25-L26

**Comment by d4mation** [comment]
I granted you read access to that Repository the other day. You will need to accept it.

**Comment by objectsweb** [comment]
- Done, Check please.

**Comment by d4mation** [comment]
Confirmed
