### ISSUE TITLE
Subscribe Button on Frontend for Courses does not utilize the Subscribe text set in the Settings

### ISSUE THREAD

**Issue by d4mation** [dragonslayerindustries/learndash-mailchimp#45]
If this is expected functionality, maybe the field description needs to be clearer? 

It seems that currently, the Subscribe Message setting is only used if the User is _registering_ for a Course, but not if they have _already been registered_ and decide to Subscribe afterwards.

![image](https://user-images.githubusercontent.com/7770631/29779207-d9ff7980-8bdf-11e7-87cb-f5fc77bc47f7.png)

![image](https://user-images.githubusercontent.com/7770631/29779336-4278e8d4-8be0-11e7-860f-48a72414787f.png)

**Comment by objectsweb** [comment]
Message now is "Registration Subscribe message". 
Thanks.

**Comment by d4mation** [comment]
Confirmed
