### ISSUE TITLE
[learndash_mc] shortcode outputs nothing for unsubscribed Users

### ISSUE THREAD

**Issue by d4mation** [dragonslayerindustries/learndash-mailchimp#46]
I don't think this is how it is intended to function. It seems pretty odd for it to output "Subscribed!" for already-subscribed Users but absolutely nothing for unsubscribed users. Shouldn't it output a button to subscribe or something? I can't think of a use case for it if it doesn't.

**Comment by objectsweb** [comment]
- Are you meaning unsubscribed users, users who didn't subscribe the course? 
I think any user that didn't subscribe the course have the button to subscribe, is that right?

**Comment by d4mation** [comment]
Users who are not subscribed to the MailChimp List.

For example, you place the `[learndash_mc]` shortcode in a Blog Post using the correct value for `course_id` to point at your course. This means anyone who can view the Blog Post can see the output of the Shortcode.

I attempted both users enrolled in the Course and not enrolled in the Course and if they were not subscribed to the MailChimp List, there was no output.

**Comment by objectsweb** [comment]
- Done, Please check.

**Comment by d4mation** [comment]
Confirmed
