### ISSUE TITLE
Settings notices repeated

### ISSUE THREAD

**Issue by brashrebel** [dragonslayerindustries/learndash-mailchimp#48]
Not occurring for every notice but there are a few situations when hitting save changes in the plugin's settings where the admin notices appear twice like this:
<img width="339" alt="screen shot 2017-09-09 at 4 01 24 am" src="https://user-images.githubusercontent.com/4993131/30238349-9fe156aa-9513-11e7-8197-f565716bc9eb.png">

Also, can we please change "Should Enter API key" to "Please enter an API key"?

**Comment by objectsweb** [comment]
please check again now.

**Comment by brashrebel** [comment]
Looks great!
