### ISSUE TITLE
Cannot create new LearnDash Content Types

### ISSUE THREAD

**Issue by d4mation** [dragonslayerindustries/learndash-mailchimp#51]
Tested Topics and Lessons explicitly. Likely happens on Courses and maybe Quizzes as well.

Reproductions steps:
- Have LD Mailchimp active
- Attempt to create one of the above content types

You'll hit a WSOD. Haven't determined the actual cause of the error yet. Just know that deactivating LD Mailchimp made it go away.

**Comment by d4mation** [comment]
So, yeah. That's a pretty glaring problem.

```
[23-Oct-2017 12:44:30 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function Ld_MailChimp_Add_Segment_List() in /srv/www/learndash/htdocs/wp-content/plugins/learndash-mailchimp/includes/classes/admin/Ld_MailChimp_Settings_Course.php:78
Stack trace:
#0 /srv/www/learndash/htdocs/wp-includes/class-wp-hook.php(298): Ld_MailChimp_Settings_Course->ls_mailchimp_update_segment_name(56, Object(WP_Post), Object(WP_Post))
#1 /srv/www/learndash/htdocs/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(57, Array)
#2 /srv/www/learndash/htdocs/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#3 /srv/www/learndash/htdocs/wp-includes/post.php(3484): do_action('post_updated', 56, Object(WP_Post), Object(WP_Post))
#4 /srv/www/learndash/htdocs/wp-includes/post.php(3583): wp_insert_post(Array, false)
#5 /srv/www/learndash/htdocs/wp-admin/includes/post.php(378): wp_update_post(Array)
#6 /srv/www/learndash/htdocs/wp-admin/post.php(193): edit_post()
#7 {main}
  thrown in /srv/www/learndash/htdocs/wp-content/plugins/learndash-mailchimp/includes/classes/admin/Ld_MailChimp_Settings_Course.php on line 78
```

**Comment by brashrebel** [comment]
Just hit this. Makes testing pretty hard.

**Comment by d4mation** [comment]
Really? In my own testing it appeared to be fixed. Could you check for any errors in `/wp-content/debug.log`?

**Comment by brashrebel** [comment]
I don't have that file but in my other logs I find nothing.

**Comment by d4mation** [comment]
You should be able to cause that file to appear by having the following Constants set: https://codex.wordpress.org/Debugging_in_WordPress#Example_wp-config.php_for_Debugging

I just have a separate terminal window open and run `tail -f debug.log` within the `/wp-content/` directory of the local site I'm testing. It then automatically shows the most recent additions to the file within that tab in terminal.

**Comment by brashrebel** [comment]
Had that already and it generated no file.

**Comment by d4mation** [comment]
Do you have any other plugins active? Running the beta for LD Mailchimp and LearnDash v2.4.7.2 I can't replicate this. Tested by making a Topic and it went through successfully.

Here's the debug info from RBP Support for my install. The "No plugin info found" bit is a bug with LearnDash where it somehow shows as two plugins. I have no idea why it does that.
```
= RBP_Support v1.0.4 =
Loaded from: /srv/www/learndash/htdocs/wp-content/plugins/learndash-mailchimp/includes/rbp-support/rbp-support.php

= Installed Plugins =
Akismet: 3.2
Column Shortcodes: 0.6.9
Custom Sidebars: 2.1.1.2
Debug Bar: 0.8.4
Debug Bar Transients: 0.5
Easy Digital Downloads: 2.8.8
Easy Digital Downloads - iDevAffiliate: 1.2.0
Embed Any Document: 2.2.5
Google Doc Embedder: 2.6.2
Hello Dolly: 1.6
LearnDash - Gradebook: 1.1.7
LearnDash - MailChimp: 1.0.0b1
LearnDash - Slack: 1.2.0b2
LearnDash EDD Integration Plugin: 1.0.3
LearnDash LMS: 2.4.7.2
LearnDash LMS - Notifications: 1.1.0-beta.4
Query Monitor: 2.13.2
Quick Page/Post Redirect Plugin: 5.1.8
Restrict Content: 2.1.3
Simply Show Hooks: 1.2.1
Theme My Login: 6.4.5
Under Construction: 1.22
User Switching: 1.0.9
WPAchievements: 2.01
WP Clone by WP Academy: 2.2.2

= Active Plugins =
LearnDash LMS: 2.4.7.2
LearnDash - MailChimp: 1.0.0b1
No Plugin Data found for Plugin at /srv/www/learndash/htdocs/wp-content/plugins/sfwd-lms/sfwd_lms.php

= Active Theme =
Name: Twenty Sixteen
Version: 1.3
Theme URI: https://wordpress.org/themes/twentysixteen/
Author URI: https://wordpress.org/

= PHP Info =
Version: 7.0.18-1+deb.sury.org~trusty+1
```

**Comment by brashrebel** [comment]
I don't know how to generate that RBP support info. Can't find anything in the admin.

I'm running the same plugins, same versions and 7.0.3 PHP. Nothing else.

**Comment by d4mation** [comment]
It isn't something user-facing. It gets attached to all support emails that get sent out. But it sounds like you've got a solid setup. Strange...

**Comment by brashrebel** [comment]
I can't even see a way to send out the....oh does it only appear if I enter a valid RBP license?

**Comment by d4mation** [comment]
Yep. It only shows if the License is Active and Valid. So if it eventually expires, the support form goes away too :+1:

**Comment by d4mation** [comment]
You could always forcibly output the debug information though. Place this somewhere in the code:

`var_dump( LDMAILCHIMP()->support->debug_file() );`

**Comment by brashrebel** [comment]
"somewhere in the code" like where exactly?

**Comment by d4mation** [comment]
Should be able to place it anywhere. `LDMAILCHIMP()` returns the singleton of the main plugin class. Putting it at the bottom of the main plugin file just after where `LDMAILCHIMP()` is first run should be a sure-fire way to get the data.

**Comment by brashrebel** [comment]
gone page. much errors.

**Comment by d4mation** [comment]
Running that broke it for you? I did the exact same thing and it worked for me.

![image](https://user-images.githubusercontent.com/7770631/32375533-5e1e1d76-c078-11e7-8187-054766f1eb04.png)

![image](https://user-images.githubusercontent.com/7770631/32375546-6d95800a-c078-11e7-991d-de1ef2890fb8.png)

**Comment by brashrebel** [comment]
Here's what I got: https://cloudup.com/cpww0ZXa474

**Comment by d4mation** [comment]
That is an error generated by RBP_Support and is a LearnDash bug. It has to do with it somehow loading as two plugins in the `active_plugins` Array. I have literally _no idea_ why it does that.

However, that should have no bearing on this issue since that will only happen when sending off the email.

Could you copy-paste the Debug Info from the Chrome Inspector into here so it has all the nice line breaks?

**Comment by d4mation** [comment]
I tested this in PHP v5.5.38 as well and was still unable to replicate this. It is a little blurry, but it looks like from your screenshot of the output that you were using PHP v7.0.3 above. I was using PHP v7.0.18 which is similar enough that I doubt it would be causing any issues here...

**Comment by brashrebel** [comment]
```
= RBP_Support v1.0.4 =
Loaded from: /app/public/wp-content/plugins/learndash-mailchimp/includes/rbp-support/rbp-support.php
= Installed Plugins =
Easy Digital Downloads: 2.7.11
Easy Digital Downloads - MailChimp: 2.5.6
LearnDash - MailChimp: 1.0.0b1
LearnDash LMS: 2.4.7.2
= Active Plugins =
LearnDash - MailChimp: 1.0.0b1
LearnDash LMS: 2.4.7.2
No Plugin Data found for Plugin at /app/public/wp-content/plugins/sfwd-lms/sfwd_lms.php
= Active Theme =
Name: Twenty Seventeen
Version: 1.1
Theme URI: https://wordpress.org/themes/twentyseventeen/
Author URI: https://wordpress.org/
= PHP Info = Version: 7.0.3
```

**Comment by d4mation** [comment]
Yeah, that's very odd. At this point, my only guess is that your local environment must be blocking the connection to the API Endpoint(s) and therefore cannot verify the API Key.

Testing it on a remote server like `dev.realbigplugins.com` would help confirm this, or using a different configuration like VVV for your local environment.

Alternatively, you could add the following at https://github.com/dragonslayerindustries/learndash-mailchimp/blob/f0062de915e2612fcc3cf982f914cd7b933d361d/learndash-mailchimp.php#L284-L286

![image](https://user-images.githubusercontent.com/7770631/32390635-91924a2e-c0a5-11e7-88f4-7d55f7f308d8.png)

`$this->mailchimp_api` is only false if a completely bogus key was fed into it (Specifically, one without a hyphen).  This should help us know if perhaps the API Call is being blocked/failing outside of the normal returned value from MailChimp for an invalid key.

**Comment by d4mation** [comment]
This is very strange. Looking at the debug file here, there's nothing that sticks out.

Unless we can get PHP to produce meaningful errors for this or I can reproduce it I'm not sure out to proceed. When it happened for me before, it went straight to `/wp-content/debug.log`.

**Comment by brashrebel** [comment]
[debug.log](https://github.com/dragonslayerindustries/learndash-mailchimp/files/1442450/debug.log)
Got one to generate finally.

**Comment by d4mation** [comment]
Could you try deleting that file and reverting any changes you've made to
the plugin (so, back to the HEAD of `develop`) so that you can generate a
fresh one?

There's a ton of stuff in there in relation to the debug file for
RBP-support which is making it difficult to find what is actually happening.

So revert changes, delete the file, create a new empty debug.log, then
immediately try to save a LearnDash Topic or something.

**Comment by brashrebel** [comment]
If I delete the line dumping the RBP support stuff, nothing ends up in the debug file. It is completely empty. It does get filled up every page load with that debug line included and that was the only change I had.

**Comment by d4mation** [comment]
That's really strange... Can you reproduce this, @joelworsham?

**Comment by joelworsham** [comment]
I tried the original reproduction steps above.

1. Installed the plugin (first time ever)
2. Immediately went to Topics and clicked "Add New"
3. Entered generic title/content and hit "Publish"
4. It created it fine.

No problems.

**Comment by d4mation** [comment]
Fixed it. I had called `wp_is_error()` rather than `is_wp_error()` in one of the functions that was being called on both the Settings Page and the Course Edit page. For some reason it never crashed on me until today though. It also did not leave behind any kind of errors until I managed to trigger it on the Settings Page by creating Segments for pre-existing Courses.
