### ISSUE TITLE
Fatal error - missing MailChimp API files

### ISSUE THREAD

**Issue by brashrebel** [dragonslayerindustries/learndash-mailchimp#52]
Looks like the MailChimp API stuff got moved out of the plugin and into a git submodule or something. Anyway, I can't test right now because it throws a fatal error:

```
Fatal error: require_once(): Failed opening required '/Users/kylemaurer/Documents/Websites/plugins.dev/wp-content/plugins/learndash-mailchimp//includes/mailchimp-api/src/MailChimp.php' (include_path='.:/Applications/XAMPP/xamppfiles/lib/php') in /Users/kylemaurer/Documents/Websites/plugins.dev/wp-content/plugins/learndash-mailchimp/learndash-mailchimp.php on line 187
```
I'm certain there is just something else I need to do. If you're going to use this approach, please provide me with detailed instructions on how to make it work. Thanks!

**Comment by d4mation** [comment]
This will correct itself if you download from the releases tab or run `git clone --recursive https://github.com/dragonslayerindustries/learndash-mailchimp.git`

**Comment by d4mation** [comment]
Alternatively, you should be able to run `git submodule update --init --recursive` if you already have the repository cloned pre-submodules.
