### ISSUE TITLE
API key sometimes being incorrectly shown as invalid

### ISSUE THREAD

**Issue by brashrebel** [dragonslayerindustries/learndash-mailchimp#53]
Tried on three different sites, each time with three different API keys. On the first two sites each key was invalid. On the third site, all of them were shown as valid. The only obvious difference was a more recent version of PHP. 7.0 on the working site and 5.5 on the other two. There might be other subtle differences but nothing obvious. DesktopServer for the first two and Local by Flywheel for the others.

**Comment by d4mation** [comment]
Could you send me the API Key you're testing with in Slack? I was never able to reproduce this.

**Comment by d4mation** [comment]
I just tried by generating a new API Key and using that and it is still properly is showing as "valid".

I am running PHP 7.0 locally, but I don't think this is the cause. I'm using the same MailChimp API Class that @objectsweb was using (I just placed it into a Submodule), but it looks like I could use this [API method](http://developer.mailchimp.com/documentation/mailchimp/reference/ping/#read-get_ping) instead and see if that works for you. Right now I'm just accessing the root of the API and checking if it returns errors.

**Comment by d4mation** [comment]
I just changed up the code a little for checking API Key validity. Could you pull `develop` and try again?

**Comment by brashrebel** [comment]
No difference on my PHP 5.5 site. All three keys still show invalid.

**Comment by d4mation** [comment]
Could you send me the API Key you're testing with in Slack? This would make it quicker for me to determine if it is a problem with the old PHP version.

**Comment by d4mation** [comment]
Took a while, but I got PHP v5.5.38 set up in my local environment.

I tested all three of your API Keys and was not able to replicate this :/

Maybe this is something specific to Desktop Server/Local by Flywheel? Maybe somehow the API Calls aren't making it out correctly? If the API Call fails, the code will assume the API Key is invalid.

**Comment by d4mation** [comment]
It may be worth testing on `dev.realbigplugins.com` to see how it functions on a non-local server.

**Comment by d4mation** [comment]
Alternatively, you could add the following at https://github.com/dragonslayerindustries/learndash-mailchimp/blob/f0062de915e2612fcc3cf982f914cd7b933d361d/learndash-mailchimp.php#L284-L286

![image](https://user-images.githubusercontent.com/7770631/32390635-91924a2e-c0a5-11e7-88f4-7d55f7f308d8.png)

`$this->mailchimp_api` is only false if a completely bogus key was fed into it (Specifically, one without a hyphen).  This should help us know if perhaps the API Call is being blocked/failing outside of the normal returned value from MailChimp for an invalid key.

**Comment by d4mation** [comment]
Reported fixed. Possibly due to fixing #51
