### ISSUE TITLE
Update segment name if course name is changed

### ISSUE THREAD

**Issue by brashrebel** [dragonslayerindustries/learndash-mailchimp#7]
We'll need some simple check when a course is updated that looks to see if the title has changed. If it has changed, update the corresponding segment name within MailChimp.

**Comment by objectsweb** [comment]
OK it will be done, but can we change the segment name and send it to mail-chimp without affecting the course name itself?

**Comment by brashrebel** [comment]
Hmmm, I'm not entirely sure. The only thing that I think is really important is that the segments in MailChimp match the course names on the site always. So if the course names change, the segment names should get updated too. They should just always match.

**Comment by objectsweb** [comment]
OK Clear.
